version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: katepavlenko/lab4:compose-django
    container_name: django
    networks:
      - public
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monitoring
    image: katepavlenko/lab4:compose-monitoring
    container_name: monitoring
    depends_on:
      - django
    networks:
      - bridge

networks:
  public:
    driver: bridge
  bridge:
    driver: bridge